# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Gua-tk
tagline:          ''
description:      ''
url:              https://gua-tk.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
baseurl:          https://gua-tk.github.io/ # the subpath of your site, e.g. /blog

twitter_username: gua_tk
github_username:  Gua-tk

author: Axlfc
name: Axl

paginate:         5

# Custom vars
version:

github: Gua-tk
repo:
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
